version: '3'

######### Services ###################################

services:
  # Server container
  web:
    container_name: book-web
    build:
      context: docker/dev/nginx
      dockerfile: Dockerfile
    volumes:
      - ./book-backend/app/public:/var/www/app/public
      - ./docker/laravel/storage/app/public:/var/www/app/public/storage
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

  # PHP FastCGI Process Manager container
  backend:
    container_name: book-backend
    build:
      context: book-backend
      dockerfile: Dockerfile
    environment:
      # If you down want to use xDebug, set remote_enable=0
      XDEBUG_CONFIG: "remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - './docker/laravel/storage/app:/var/www/app/storage/app'
      - './docker/laravel/storage/logs/:/var/www/app/storage/logs'
    depends_on:
      - db

  # MySQL database container
  db:
    container_name: book-db
    image: 'mysql:8.0'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'Ap0359495341'
      MYSQL_DATABASE: 'book'
      MYSQL_USER: 'administrator'
      MYSQL_PASSWORD: 'Ap0359495341'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'database:/var/lib/mysql'
      - ./docker/mysql/mysql-files:/var/lib/mysql-files
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-pAp0359495341' ]
      retries: 3
      timeout: 5s
  # Client container
  frontend:
    container_name: book-frontend
    build:
      context: book-frontend
      dockerfile: Dockerfile
######### Volumes ###################################

volumes:
  database:
    driver: local
  redis:
    driver: local
