FROM mysql:8.0

ENV \
# MYSQL_USER=root \
  MYSQL_PASSWORD=Ap0359495341\
  MYSQL_ROOT_PASSWORD=Ap0359495341 \
  TZ=Asia/Tokyo

COPY ./my.cnf /etc/mysql/conf.d/my.cnf
RUN chmod 644 /etc/mysql/conf.d/my.cnf